//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string HELON = "helon";
        
        public const string HELBREAK = "helbreak";
        
        public const string HELRIGHTBREAK = "helrightbreak";
        
        public const string HELLEFTBREAK = "helleftbreak";
        
        public const string FACEBREAK = "facebreak";
        
        public const string BACKBREAK = "backbreak";
    }
}
